### PR TITLE
Add maintenance

### PR DESCRIPTION
**Pull request by NikolaRHristov**
Adds maintenance and dependabot

### CODE REVIEW

**Comment by NikolaRHristov** [comment]
Generated with [@yesmaintenance/scripts](https://github.com/yesmaintenance/npm) `maintenance workflows`

**Comment by ThePrimeagen** [comment]
Hey @nikolaxhristov you said looks good to me on a different PR, which one should I choose?

**Comment by ThePrimeagen** [comment]
This one seems to be the most complete

**Comment by NikolaRHristov** [comment]
Dear, @ThePrimeagen, the three of them do the same thing. This one has `pnpm` and `Dependabot` setup with `pnpm` cache. The #5 is using `yarn` with cache, as well. The #4 is pretty basic but functional.

**Comment by NikolaRHristov** [comment]
This is the most complete one and tests on three different node versions 14, 16 and 18.

**Comment by NikolaRHristov** [comment]
Merge this. @ThePrimeagen

**Comment by NikolaRHristov** [comment]
This is how a successful run looks like https://github.com/nikolaxhristov/undefined/actions/runs/3388576406 and you can add it as a badge like this:

```md
<a
	href="https://github.com/nikolaxhristov/undefined/actions/workflows/node.yml">
	<img
		src="https://img.shields.io/github/workflow/status/nikolaxhristov/undefined/Node?label=Build&logo=node.js&color=black&logoColor=white&labelColor=black&logoWidth=15"
	/>
</a>
```

<a
	href="https://github.com/nikolaxhristov/undefined/actions/workflows/node.yml">
	
</a>

After the tests are completed you would need to setup a build step, which outputs artifacts like this https://github.com/lightrix/npm/blob/main/.github/workflows/node.yml#L44-L49 which you can then use to commit directly to the repository like so:

```yaml
name: Commit

on:
    workflow_run:
        workflows: [Node]
        types: [completed]

jobs:
    prepare:
        uses: undefined/.github/workflows/node.yml@master

    build:
        needs: prepare
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions/download-artifact@v3
              id: download
              with:
                  name: .-node-18-dist
            - run: |
                  cp -rf ${{steps.download.outputs.download-path}}\dist .
                  git add .
                  git config --global user.name 'Auto Build'
                  git config --global user.email 'auto-build@undefined'
                  git commit -m "Auto build"
                  git push
```

like in https://github.com/nikolaxhristov/undefined

I've added a build step but there are some things to fix mainly in 

```
Errors  Files
     4  src/collapse.ts:1
     3  src/enum.ts:1
     2  src/file.ts:2
     3  src/test/collapse.spec.ts:3
     3  src/test/name.spec.ts:3
     3  src/test/run.ts:3
    16  src/types.ts:6
     6  src/undefined-runner.ts:1
     5  src/undefined.ts:1
    28  src/unions.ts:6
     6  src/utils.ts:1
```

**Comment by NikolaRHristov** [comment]
I'll try to fix some of them out of fun but I don't want to mess with your code.

**Comment by NikolaRHristov** [comment]
This is about as clean as you can get https://github.com/nikolaxhristov/undefined/commit/4ff0d17e0fa6e2497925f28c7df147f72008a5df but there are still some type errors mainly:

```
src/test/config.collapse.ts(1,1): error TS1208: 'config.collapse.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
src/test/config.collapse.ts(1,6): error TS2300: Duplicate identifier 'BaseName2'.
src/test/config.export.declare.ts(1,1): error TS1208: 'config.export.declare.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
src/test/config.name.ts(1,1): error TS1208: 'config.name.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
src/test/config.name.ts(1,6): error TS2300: Duplicate identifier 'barUnion'.
src/test/config.name.ts(11,6): error TS2300: Duplicate identifier 'BaseName1'.
src/test/config.name.ts(16,6): error TS2300: Duplicate identifier 'BaseName2'.
src/test/config.name.ts(22,6): error TS2300: Duplicate identifier 'BaseName3'.
src/test/config.name.ts(28,6): error TS2300: Duplicate identifier 'BaseName4'.
src/test/config.name.ts(33,6): error TS2300: Duplicate identifier 'BaseName5'.
src/test/config.sumtype.ts(1,1): error TS1208: 'config.sumtype.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
src/test/config.sumtype.ts(3,6): error TS2300: Duplicate identifier 'barUnion'.
src/test/config.sumtype.ts(7,6): error TS2300: Duplicate identifier 'BaseName1'.
src/test/config.sumtype.ts(13,6): error TS2300: Duplicate identifier 'BaseName2'.
src/test/config.sumtype.ts(18,6): error TS2300: Duplicate identifier 'BaseName3'.
src/test/config.sumtype.ts(24,6): error TS2300: Duplicate identifier 'BaseName4'.
src/test/config.sumtype.ts(30,6): error TS2300: Duplicate identifier 'BaseName5'.
src/test/config.sumtype.ts(35,6): error TS2300: Duplicate identifier 'BaseName6'.
src/test/no-config.2.ts(1,1): error TS1208: 'no-config.2.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
src/test/no-config.2.ts(1,6): error TS2300: Duplicate identifier 'barUnion'.
src/test/no-config.2.ts(15,6): error TS2300: Duplicate identifier 'BaseName1'.
src/test/no-config.2.ts(21,6): error TS2300: Duplicate identifier 'BaseName2'.
src/test/no-config.2.ts(25,6): error TS2300: Duplicate identifier 'BaseName3'.
src/test/no-config.2.ts(30,6): error TS2300: Duplicate identifier 'BaseName4'.
src/test/no-config.2.ts(35,6): error TS2300: Duplicate identifier 'BaseName5'.
src/test/no-config.2.ts(40,6): error TS2300: Duplicate identifier 'BaseName6'.
src/test/no-config.4.ts(1,1): error TS1208: 'no-config.4.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.
src/test/no-config.4.ts(1,6): error TS2300: Duplicate identifier 'barUnion'.
src/test/no-config.4.ts(5,6): error TS2300: Duplicate identifier 'BaseName1'.
src/test/no-config.4.ts(11,6): error TS2300: Duplicate identifier 'BaseName2'.
src/test/no-config.4.ts(16,6): error TS2300: Duplicate identifier 'BaseName3'.
src/test/no-config.4.ts(22,6): error TS2300: Duplicate identifier 'BaseName4'.
src/test/no-config.4.ts(28,6): error TS2300: Duplicate identifier 'BaseName5'.
src/test/no-config.4.ts(33,6): error TS2300: Duplicate identifier 'BaseName6'.
src/undefined.ts(3,1): error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.
src/unions.ts(41,34): error TS18048: 'typeSet' is possibly 'undefined'.
src/unions.ts(42,17): error TS18048: 'typeSet' is possibly 'undefined'.
src/unions.ts(42,17): error TS2532: Object is possibly 'undefined'.
src/unions.ts(44,6): error TS18048: 'typeSet' is possibly 'undefined'.
src/unions.ts(44,6): error TS2532: Object is possibly 'undefined'.
src/unions.ts(49,5): error TS18048: 'typeSet' is possibly 'undefined'.
src/unions.ts(70,8): error TS2532: Object is possibly 'undefined'.
src/unions.ts(72,15): error TS2532: Object is possibly 'undefined'.
src/unions.ts(73,17): error TS2532: Object is possibly 'undefined'.
src/unions.ts(74,13): error TS2532: Object is possibly 'undefined'.
src/unions.ts(165,14): error TS2532: Object is possibly 'undefined'.
src/unions.ts(165,34): error TS2532: Object is possibly 'undefined'.
src/unions.ts(167,8): error TS2532: Object is possibly 'undefined'.
src/unions.ts(185,41): error TS18048: 'type0' is possibly 'undefined'.
src/unions.ts(185,41): error TS2769: No overload matches this call.
  Overload 1 of 4, '(iterable?: Iterable<readonly [Type, string]> | null | undefined): Map<Type, string>', gave the following error.
    Argument of type '[Type, string | undefined][]' is not assignable to parameter of type 'Iterable<readonly [Type, string]>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<[Type, string | undefined], any>' is not assignable to type 'IteratorResult<readonly [Type, string], any>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
          Type 'IteratorYieldResult<[Type, string | undefined]>' is not assignable to type 'IteratorResult<readonly [Type, string], any>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
            Type 'IteratorYieldResult<[Type, string | undefined]>' is not assignable to type 'IteratorYieldResult<readonly [Type, string]>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
              Type '[Type, string | undefined]' is not assignable to type 'readonly [Type, string]'.
                Type at position 1 in source is not compatible with type at position 1 in target.
                  Type 'string | undefined' is not assignable to type 'string'.
                    Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 4, '(entries?: readonly (readonly [Type, string])[] | null | undefined): Map<Type, string>', gave the following error.
    Argument of type '[Type, string | undefined][]' is not assignable to parameter of type 'readonly (readonly [Type, string])[]'.
      Type '[Type, string | undefined]' is not assignable to type 'readonly [Type, string]'.
src/unions.ts(186,41): error TS18048: 'type1' is possibly 'undefined'.
src/unions.ts(186,41): error TS2769: No overload matches this call.
  Overload 1 of 4, '(iterable?: Iterable<readonly [Type, string]> | null | undefined): Map<Type, string>', gave the following error.
    Argument of type '[Type, string | undefined][]' is not assignable to parameter of type 'Iterable<readonly [Type, string]>'.
  Overload 2 of 4, '(entries?: readonly (readonly [Type, string])[] | null | undefined): Map<Type, string>', gave the following error.
    Argument of type '[Type, string | undefined][]' is not assignable to parameter of type 'readonly (readonly [Type, string])[]'.
src/unions.ts(196,37): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(198,14): error TS2532: Object is possibly 'undefined'.
src/unions.ts(199,23): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(200,23): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(206,20): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(206,31): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(210,47): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(210,58): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
src/unions.ts(226,11): error TS2339: Property 'propKey' does not exist on type 'UnionizeableProperty | undefined'.
src/unions.ts(226,20): error TS2339: Property 'propValue' does not exist on type 'UnionizeableProperty | undefined'.
```

**Comment by ThePrimeagen** [comment]
yes, everything within the test folder should probably be ignored, but more so, we should probably move those to an inner folder and ignore all of them.  that way we can still type check the tests.

**Comment by ThePrimeagen** [comment]
that's just me thinking outloud

**Comment by ThePrimeagen** [comment]
i cannot spend any more time on this.  

i am not going to go with this solution.  it just changed SO many things and ended up causing a bot load of issues.

**Comment by ThePrimeagen** [comment]
sorry, i wanted this to work out.  if you want to try again with _just CI_ to start with. that would be great.  just node running a test fail on fail pass on pass.  grand!  but too much change just causes huge headaches.

**Comment by NikolaRHristov** [comment]
Oh yeah sure.

**Comment by NikolaRHristov** [comment]
https://github.com/ThePrimeagen/undefined/pull/9 @ThePrimeagen

**Pull request merged**
