### PR TITLE
feat: added ci on prs

### PR DESCRIPTION
**Pull request by Her0elt**

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
this is awesome!!!

**Comment by ThePrimeagen** [comment]
Okay, I don't really know which one to choose. I have three of the same PR. Could you help me decide which one is correct? I don't really know GitHub CI

**Comment by Her0elt** [comment]
@ThePrimeagen, i would say its kind of up to what you want with your CI, #3 is def the most advanced, and covers more than just testing, i especially like dependabot which keeps your dependencies up to date, but if its not set to auto merge and you get to lazy you might have a repo like this.
image

So if your looking for the whole package i would go with #3, but if you want to be able to debug your ci config and possibly extend it to do other things, and maybe learn github actions aswell, this pr or maybe #4 might be the best option. Mine also useses yarn which you already use in this project, if im gonna swing it in my direction :smile: . But if you want the best option id say merge em all the more ci and testing the better :laughing:

**Comment by ThePrimeagen** [comment]
MOAR CI
MOAR BETTER

but really, thanks for the honest approach.  i just need to make sure things are running per pr and i really want to avoid learning anything ;)

**Pull request closed without merging**
